### ISSUE TITLE
TODO: MaskGeneration

### ISSUE THREAD

**Issue by 51N84D** [cc-ai/kdb#116]
* [ ] Training on Unity Urban + Suburban *Méli*
* [ ] Training on WD *Méli*
* [ ] Training on heavier flooded images (Unity)
* [ ] Conditioning on depth and segmentation *Méli*
* [ ] Create standard test set (25 images) to evaluate MaskGen on *Sun*
* [ ] Determine evaluation metrics for MaskGen  *Sun* [metrics paper](https://www.ri.cmu.edu/pub_files/pub4/unnikrishnan_ranjith_2005_2/unnikrishnan_ranjith_2005_2.pdf)
  * [ ] M-IOU
  * [ ] Pixel Accuracy
  * [ ] Hole detection
* [ ] Domain Adaptation *TianYu*
  * [ ] Feature discriminator operates on each domain (3 domains -> 3 classes)
  * [ ] Try Sim2Real

**Comment by sashavor** [comment]
* [ ] Create evaluation set
* [ ] Establish evaluation metric

**Comment by vict0rsch** [comment]
(write your names next to items you want to own 🥇)

**Comment by melisandeteng** [comment]
Depth maps of the WatchDogs dataset computed with MegaDepth model can be found in `/network/tmp1/ccai/data/Ubisoft_LaForge_ClimateChange_DataSet/` . 
They were computed on the non-flooded images resized to 512x384 pixels.
Depth can be misestimated for thin objects or when there are strong shadows for example. 

<img src="https://user-images.githubusercontent.com/34208548/78571140-dc991680-77f3-11ea-9251-e0399d9cafe5.png" width="200"  /> <img src="https://user-images.githubusercontent.com/34208548/78571099-cd19cd80-77f3-11ea-8af7-f9ce320c7462.png" width="200"  />

**Comment by vict0rsch** [comment]
Hmm this isn't really good, is it? What's a representative inference @melisandeteng ? (I mean, not a worst nor best case scenario)

**Comment by vict0rsch** [comment]
Is this something we want in the test images?

<img width="835" alt="2020-04-10 at 12 38" src="https://user-images.githubusercontent.com/9283470/79006985-3bc69600-7b28-11ea-8fa7-ff5eb61405d5.png">
