### ISSUE TITLE
Tianyu's TODO list

### ISSUE THREAD

**Issue by AGIArchitect** [cc-ai/kdb#118]
Checklist from April. 6th

Notes
✅ means finished
❌ means canceled
❓ means questions here (ready to report on ML check) 

✅ Learning to Adapt Structured Output Space for Semantic Segmentation: arxiv.org/pdf/1802.10349.pdf

✅ ADVENT: Adversarial Entropy Minimization for Domain Adaptation in Semantic Segmentation: arxiv.org/pdf/1811.12833.pdf

- [ ] Domain Adaptation for Structured Output via Discriminative Patch Representations: arxiv.org/pdf/1901.05427v3.pdf

- [ ] DADA: Depth-aware Domain Adaptation in Semantic Segmentation: arxiv.org/abs/1904.01886

- [ ] Train a CycleGAN on the cluster

- [ ] Read the trainer.py code in MUNIT original repo \check
